language: node_js
node_js: '6'
install: npm install
script:
  - npm run development:client
  - npm run development:server
  - node ./dist/js/server.js &
  - npm run karma:client
  - npm run production:client
  - npm run production:server
after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < doc/coverage/client/report-lcov/lcov.info
addons:
  code_climate:
    repo_token: 2ed0fdccdf32de9d1ac308c418d63c9684cc547231fec9dc3fa822e971c57bff
deploy:
  provider: npm
  email: 'info@crazysquirrel.ru'
  api_key: '443206b0-d7ea-47eb-89ca-9ff2e6ec246b'
  skip_cleanup: true
  on:
    tags: true
    branch: master
